import { Customer, Product, Wholesaler } from './types';

export const INITIAL_CUSTOMERS: Customer[] = [
  { 
    id: 1, 
    name: 'Afrah', 
    email: 'afrah@example.com', 
    phone: '9630080', 
    telegramId: '@afrah', 
    redboxId: 1001,
    address: 'G. Vaffushi, Male',
    notes: 'VIP customer. Prefers quick delivery.',
    tags: ['VIP', 'Frequent Buyer'],
    createdAt: new Date('2023-01-15T10:00:00Z').toISOString(),
    maximumCreditLimit: 500,
    creditBlocked: false
  },
  { id: 2, name: 'Rayyaan', email: 'rayyaan@example.com', phone: '', telegramId: '', redboxId: 1002, maximumCreditLimit: 500, creditBlocked: false },
  { id: 3, name: 'Mayyash', email: 'mayyash@example.com', phone: '', telegramId: '', redboxId: 1003, maximumCreditLimit: 500, creditBlocked: false },
  { id: 4, name: 'Thoriqul', email: 'thoriqul@example.com', phone: '', telegramId: '', redboxId: 1004, maximumCreditLimit: 500, creditBlocked: false },
  { id: 5, name: 'Zahuwaan', email: 'zahuwaan@example.com', phone: '', telegramId: '', redboxId: 1005, maximumCreditLimit: 500, creditBlocked: false },
  { id: 6, name: 'Shamveel', email: 'shamveel@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 7, name: 'Ameel', email: 'ameel@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 8, name: 'Hussain', email: 'hussain@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 9, name: 'Adam', email: 'adam@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 10, name: 'Emran', email: 'emran@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 11, name: 'Soppe', email: 'soppe@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 12, name: 'Hashim', email: 'hashim@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 13, name: 'Meem', email: 'meem@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 14, name: 'Husham', email: 'husham@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 15, name: 'Afwan', email: 'afwan@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 16, name: 'Siyadh', email: 'siyadh@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 17, name: 'Wittu', email: 'wittu@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 18, name: 'Solah', email: 'solah@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 19, name: 'Khathoub', email: 'khathoub@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 20, name: 'Niyaz', email: 'niyaz@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 21, name: 'Ranga', email: 'ranga@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 22, name: 'Alamgir', email: 'alamgir@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 23, name: 'Haroon', email: 'haroon@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 24, name: 'Habibur', email: 'habibur@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 25, name: 'Haisham', email: 'haisham@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 26, name: 'Sajib', email: 'sajib@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 27, name: 'Mofazzal', email: 'mofazzal@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 28, name: 'Nahudhan', email: 'nahudhan@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 29, name: 'Saavi', email: 'saavi@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 30, name: 'Mahfooz', email: 'mahfooz@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 31, name: 'Parvez', email: 'parvez@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 32, name: 'Hafiz', email: 'hafiz@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 33, name: 'Maain', email: 'maain@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 34, name: 'Basith', email: 'basith@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 35, name: 'Zayaan', email: 'zayaan@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 36, name: 'Humeidh', email: 'humeidh@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 37, name: 'Bisru', email: 'bisru@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 38, name: 'Sumon', email: 'sumon@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 39, name: 'Sofiqul', email: 'sofiqul@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 40, name: 'Amir', email: 'amir@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 41, name: 'Rajib', email: 'rajib@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 42, name: 'Azzam', email: 'azzam@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 43, name: 'Naai', email: 'naai@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 44, name: 'Jannath', email: 'jannath@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 45, name: 'Hana', email: 'hana@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 46, name: 'Ulfath', email: 'ulfath@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 47, name: 'Dheema', email: 'dheema@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 48, name: 'Niuma', email: 'niuma@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 49, name: 'Shaffana', email: 'shaffana@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 50, name: 'Sana', email: 'sana@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 51, name: 'Raniya', email: 'raniya@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 52, name: 'Nusaika', email: 'nusaika@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 53, name: 'Nahula', email: 'nahula@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
  { id: 54, name: 'Shiyaz', email: 'shiyaz@example.com', phone: '', telegramId: '', maximumCreditLimit: 500, creditBlocked: false },
];

export const INITIAL_PRODUCTS: Product[] = [
  { id: 201, name: 'Water 500ml', price: 5.00, wholesalePrice: 2.50, stock: 100, category: 'Drinks', defaultWholesalerId: 2 },
  { id: 202, name: 'XL Energy Drink 150ml', price: 20.00, wholesalePrice: 15.00, stock: 50, category: 'Drinks', defaultWholesalerId: 2 },
  { id: 203, name: 'XL Energy Drink 250ml', price: 0.00, wholesalePrice: 0.00, stock: 30, category: 'Drinks', defaultWholesalerId: 2 },
  { id: 204, name: 'Nescafe Original', price: 15.00, wholesalePrice: 10.00, stock: 40, category: 'Drinks', defaultWholesalerId: 1 },
  { id: 205, name: 'Nescafe Mocha', price: 15.00, wholesalePrice: 10.00, stock: 40, category: 'Drinks', defaultWholesalerId: 1 },
  { id: 206, name: 'Speed', price: 15.00, wholesalePrice: 12.00, stock: 25, category: 'Drinks', defaultWholesalerId: 2 },
  { id: 207, name: 'Speed Apple', price: 15.00, wholesalePrice: 12.00, stock: 25, category: 'Drinks', defaultWholesalerId: 2 },
  { id: 208, name: 'Bitter Lemon', price: 10.00, wholesalePrice: 7.00, stock: 15, category: 'Drinks', defaultWholesalerId: 2 },
  { id: 209, name: 'Black Tea (Iced)', price: 15.00, wholesalePrice: 10.00, stock: 20, category: 'Drinks', defaultWholesalerId: 1 },
  { id: 210, name: 'Juice Petee', price: 5.00, wholesalePrice: 3.00, stock: 5, category: 'Drinks', defaultWholesalerId: 2 },
  { id: 211, name: 'Chocolate Wafer', price: 5.00, wholesalePrice: 2.50, stock: 60, category: 'Snacks', defaultWholesalerId: 3 },
  { id: 212, name: 'Murumuru', price: 15.00, wholesalePrice: 10.00, stock: 0, category: 'Snacks', defaultWholesalerId: 3 },
  { id: 213, name: "Haaroon's Badhan", price: 10.00, wholesalePrice: 6.00, stock: 10, category: 'Snacks', defaultWholesalerId: 3 },
];

export const INITIAL_WHOLESALERS: Wholesaler[] = [
  { id: 1, name: 'Global Foods Inc.', contactPerson: 'John Doe', contactNumber: '555-1234', email: 'john.d@globalfoods.com' },
  { id: 2, name: 'Island Beverages Co.', contactPerson: 'Jane Smith', contactNumber: '555-5678', email: 'jane.s@islandbev.com' },
  { id: 3, name: 'Capital City Snacks', contactPerson: 'Mr. Brown', contactNumber: '555-8765', email: 'brown@ccsnacks.com' }
];